FROM python:3.10-slim

# requires the wheel
COPY dist/*.whl .

RUN python -m pip install -U pip && pip install *.whl && pip install hypercorn && rm -f *.whl

EXPOSE 8080

CMD [ "hypercorn", "-b", "0.0.0.0:8080", "simple_api.app:app" ]